[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Artificial Intelligence Business Model Canvas: How to Build a Successful Business Using Intelligent Technologies"
